[package]
name = "tiny"
version = "1.0.0"
authors = ["Gustav Utke Kauman <gkauman@eadu.dk>"]
edition = "2018"

[dependencies]
clap = "2.33.2"
reqwest = { version = "0.10.7", features = ["blocking", "json"] }
